-- Inblog Autopublish - 치과 키워드 시드 데이터 (500개+)
-- 3축 조합: 시술명(50) x 검색의도(10) x 지역/상황(10)

-- 기본 스케줄 설정
INSERT OR IGNORE INTO schedules (name, posts_per_day, publish_times, category_weights)
VALUES ('default', 3, '["07:00","12:00","18:00"]', '{"implant":30,"orthodontics":20,"general":25,"prevention":15,"local":10}');

-- 기본 설정값
INSERT OR IGNORE INTO settings (key, value, description) VALUES
('inblog_api_key', '', '인블로그 API 키'),
('claude_api_key', '', 'Claude API 키'),
('clinic_name', '', '병원명 (콘텐츠에 직접 노출하지 않음)'),
('clinic_region', '', '병원 지역'),
('notification_email', '', '알림 수신 이메일'),
('auto_publish', 'true', '자동 발행 활성화'),
('seo_min_score', '80', 'SEO 최소 점수 (미만시 재생성)'),
('thumbnail_style', 'medical-clean', '썸네일 스타일'),
('medical_disclaimer', '본 콘텐츠는 일반적인 의료 정보 제공을 목적으로 작성되었으며, 특정 질환의 진단이나 치료를 대체하지 않습니다. 정확한 진단과 치료를 위해 반드시 치과 전문의와 상담하시기 바랍니다.', '의료 면책 문구');

-- ===== 임플란트 카테고리 (30%) =====
INSERT OR IGNORE INTO keywords (keyword, category, subcategory, search_intent, priority) VALUES
('임플란트 비용', 'implant', '비용', 'cost', 95),
('임플란트 수명', 'implant', '수명', 'info', 90),
('임플란트 과정', 'implant', '과정', 'info', 92),
('임플란트 통증', 'implant', '통증', 'info', 88),
('임플란트 종류', 'implant', '종류', 'comparison', 87),
('임플란트 부작용', 'implant', '부작용', 'info', 85),
('임플란트 수술 후 주의사항', 'implant', '주의사항', 'info', 93),
('임플란트 보험 적용', 'implant', '보험', 'cost', 91),
('임플란트 실패 원인', 'implant', '부작용', 'info', 82),
('오스템 임플란트', 'implant', '브랜드', 'comparison', 86),
('스트라우만 임플란트', 'implant', '브랜드', 'comparison', 84),
('네오 임플란트', 'implant', '브랜드', 'comparison', 80),
('디오 임플란트', 'implant', '브랜드', 'comparison', 79),
('임플란트 브릿지 차이', 'implant', '비교', 'comparison', 83),
('앞니 임플란트', 'implant', '부위별', 'info', 88),
('어금니 임플란트', 'implant', '부위별', 'info', 89),
('임플란트 뼈이식', 'implant', '시술', 'info', 86),
('상악동 거상술', 'implant', '시술', 'info', 75),
('즉시 임플란트', 'implant', '시술', 'info', 81),
('무절개 임플란트', 'implant', '시술', 'info', 80),
('전체 임플란트', 'implant', '시술', 'info', 78),
('임플란트 오래가는 방법', 'implant', '관리', 'info', 84),
('임플란트 관리법', 'implant', '관리', 'info', 83),
('임플란트 주위염', 'implant', '부작용', 'info', 77),
('임플란트 탈락', 'implant', '부작용', 'info', 76),
('디지털 임플란트', 'implant', '시술', 'info', 74),
('네비게이션 임플란트', 'implant', '시술', 'info', 73),
('임플란트 음식 주의', 'implant', '관리', 'info', 81),
('임플란트 흡연', 'implant', '관리', 'info', 78),
('고령자 임플란트', 'implant', '대상', 'info', 82),
('당뇨 임플란트', 'implant', '대상', 'info', 80),
('골다공증 임플란트', 'implant', '대상', 'info', 79),
('임플란트 치료 기간', 'implant', '기간', 'info', 87),
('임플란트 1차 수술', 'implant', '과정', 'info', 76),
('임플란트 2차 수술', 'implant', '과정', 'info', 75),
('임플란트 보철물 종류', 'implant', '종류', 'comparison', 74),
('지르코니아 임플란트 크라운', 'implant', '종류', 'comparison', 73),
('올온포 임플란트', 'implant', '시술', 'info', 77),
('임플란트 vs 틀니', 'implant', '비교', 'comparison', 85),
('임플란트 보증 기간', 'implant', '보증', 'info', 72),
('임플란트 재수술', 'implant', '시술', 'info', 71),
('임플란트 MRI', 'implant', '관리', 'info', 70),
('미니 임플란트', 'implant', '시술', 'info', 69),
('임플란트 식립 깊이', 'implant', '시술', 'info', 68),
('임플란트 수술 시간', 'implant', '과정', 'info', 82),
('임플란트 마취', 'implant', '과정', 'info', 76),
('임플란트 붓기', 'implant', '부작용', 'info', 80),
('임플란트 출혈', 'implant', '부작용', 'info', 74),
('임플란트 감염', 'implant', '부작용', 'info', 77),
('무치악 임플란트', 'implant', '시술', 'info', 72),

-- ===== 교정/미용 카테고리 (20%) =====
('치아 교정 비용', 'orthodontics', '비용', 'cost', 95),
('투명 교정', 'orthodontics', '종류', 'info', 93),
('인비절라인', 'orthodontics', '브랜드', 'comparison', 91),
('치아 교정 기간', 'orthodontics', '기간', 'info', 90),
('성인 교정', 'orthodontics', '대상', 'info', 89),
('부분 교정', 'orthodontics', '종류', 'info', 87),
('앞니 교정', 'orthodontics', '부위', 'info', 86),
('치아 교정 통증', 'orthodontics', '통증', 'info', 84),
('교정 후 유지장치', 'orthodontics', '관리', 'info', 83),
('설측 교정', 'orthodontics', '종류', 'info', 82),
('세라믹 교정', 'orthodontics', '종류', 'info', 81),
('치아 미백', 'orthodontics', '미백', 'info', 90),
('전문가 미백', 'orthodontics', '미백', 'info', 85),
('자가 미백', 'orthodontics', '미백', 'comparison', 80),
('미백 효과 기간', 'orthodontics', '미백', 'info', 78),
('미백 부작용', 'orthodontics', '미백', 'info', 77),
('라미네이트', 'orthodontics', '미용', 'info', 88),
('라미네이트 수명', 'orthodontics', '미용', 'info', 82),
('라미네이트 비용', 'orthodontics', '미용', 'cost', 86),
('지르코니아 크라운', 'orthodontics', '보철', 'info', 84),
('올세라믹 크라운', 'orthodontics', '보철', 'info', 79),
('잇몸 성형', 'orthodontics', '미용', 'info', 76),
('거미스마일 교정', 'orthodontics', '미용', 'info', 74),
('돌출입 교정', 'orthodontics', '종류', 'info', 85),
('턱교정', 'orthodontics', '종류', 'info', 78),
('급속 교정', 'orthodontics', '종류', 'info', 80),
('교정 발치', 'orthodontics', '과정', 'info', 79),
('교정 고무줄', 'orthodontics', '관리', 'info', 72),
('교정 와이어 교체', 'orthodontics', '과정', 'info', 71),
('교정 중 음식', 'orthodontics', '관리', 'info', 75),
('소아 교정 시기', 'orthodontics', '대상', 'info', 83),
('교정 보험', 'orthodontics', '비용', 'cost', 81),
('투명 교정 vs 메탈 교정', 'orthodontics', '비교', 'comparison', 84),
('교정 재발', 'orthodontics', '부작용', 'info', 73),
('덧니 교정', 'orthodontics', '종류', 'info', 80),
('벌어진 치아 교정', 'orthodontics', '종류', 'info', 78),
('삐뚤어진 치아 교정', 'orthodontics', '종류', 'info', 79),

-- ===== 일반 치료 카테고리 (25%) =====
('충치 치료 과정', 'general', '충치', 'info', 92),
('충치 치료 비용', 'general', '충치', 'cost', 90),
('사랑니 발치', 'general', '발치', 'info', 93),
('사랑니 발치 후 주의사항', 'general', '발치', 'info', 95),
('사랑니 발치 비용', 'general', '발치', 'cost', 88),
('사랑니 발치 통증', 'general', '발치', 'info', 87),
('매복 사랑니', 'general', '발치', 'info', 85),
('신경 치료', 'general', '신경', 'info', 91),
('신경 치료 과정', 'general', '신경', 'info', 89),
('신경 치료 비용', 'general', '신경', 'cost', 87),
('신경 치료 통증', 'general', '신경', 'info', 86),
('크라운 치료', 'general', '보철', 'info', 84),
('크라운 종류', 'general', '보철', 'comparison', 82),
('크라운 비용', 'general', '보철', 'cost', 83),
('인레이 온레이', 'general', '보철', 'info', 78),
('금 인레이 vs 세라믹 인레이', 'general', '보철', 'comparison', 77),
('레진 치료', 'general', '충치', 'info', 80),
('아말감 vs 레진', 'general', '충치', 'comparison', 76),
('치아 파절', 'general', '외상', 'info', 79),
('치아 깨짐 응급처치', 'general', '외상', 'info', 81),
('잇몸 치료', 'general', '잇몸', 'info', 88),
('잇몸병 원인', 'general', '잇몸', 'info', 85),
('치주염 치료', 'general', '잇몸', 'info', 86),
('치은염 증상', 'general', '잇몸', 'info', 82),
('잇몸 출혈 원인', 'general', '잇몸', 'info', 84),
('치석 제거', 'general', '잇몸', 'info', 81),
('이갈이 치료', 'general', '기타', 'info', 77),
('턱관절 장애', 'general', '기타', 'info', 80),
('구내염 원인', 'general', '기타', 'info', 79),
('치아 흔들림 원인', 'general', '잇몸', 'info', 78),
('치아 시림 원인', 'general', '증상', 'info', 85),
('치아 통증 원인', 'general', '증상', 'info', 87),
('치아 변색 원인', 'general', '증상', 'info', 76),
('치아 마모', 'general', '증상', 'info', 73),
('치아 뿌리 염증', 'general', '증상', 'info', 77),
('치수염 증상', 'general', '증상', 'info', 75),
('브릿지 치료', 'general', '보철', 'info', 79),
('의치 종류', 'general', '보철', 'info', 74),
('틀니 종류', 'general', '보철', 'comparison', 78),
('틀니 관리법', 'general', '보철', 'info', 75),
('치아 접착', 'general', '보철', 'info', 70),
('치아 재식', 'general', '시술', 'info', 68),

-- ===== 예방/관리 카테고리 (15%) =====
('스케일링', 'prevention', '스케일링', 'info', 92),
('스케일링 비용', 'prevention', '스케일링', 'cost', 88),
('스케일링 주기', 'prevention', '스케일링', 'info', 90),
('스케일링 보험', 'prevention', '스케일링', 'cost', 86),
('스케일링 후 주의사항', 'prevention', '스케일링', 'info', 87),
('올바른 칫솔질 방법', 'prevention', '구강관리', 'info', 85),
('치실 사용법', 'prevention', '구강관리', 'info', 82),
('치간칫솔 사용법', 'prevention', '구강관리', 'info', 80),
('구강세정기 효과', 'prevention', '구강관리', 'info', 79),
('불소 도포', 'prevention', '예방', 'info', 78),
('실란트', 'prevention', '예방', 'info', 81),
('정기 검진 주기', 'prevention', '검진', 'info', 83),
('파노라마 촬영', 'prevention', '검진', 'info', 74),
('치과 엑스레이', 'prevention', '검진', 'info', 76),
('치아 보험 종류', 'prevention', '보험', 'cost', 84),
('치과 보험 활용법', 'prevention', '보험', 'cost', 82),
('건강보험 치과', 'prevention', '보험', 'cost', 80),
('임산부 치과 치료', 'prevention', '대상', 'info', 83),
('어린이 치과 검진', 'prevention', '대상', 'info', 85),
('노인 구강 관리', 'prevention', '대상', 'info', 79),
('당뇨환자 구강 관리', 'prevention', '대상', 'info', 77),
('흡연과 구강 건강', 'prevention', '관리', 'info', 78),
('음식과 치아 건강', 'prevention', '관리', 'info', 76),
('치아에 좋은 음식', 'prevention', '관리', 'info', 80),
('치아에 나쁜 습관', 'prevention', '관리', 'info', 79),
('구취 원인과 해결', 'prevention', '증상', 'info', 84),
('입마름 원인', 'prevention', '증상', 'info', 75),
('수면 중 이갈이', 'prevention', '증상', 'info', 77),
('치아 외상 응급처치', 'prevention', '응급', 'info', 81),
('유치 관리', 'prevention', '대상', 'info', 78),

-- ===== 지역/병원 카테고리 (10%) =====
('치과 선택 기준', 'local', '병원선택', 'info', 85),
('좋은 치과 고르는 법', 'local', '병원선택', 'info', 88),
('치과 공포증 극복', 'local', '경험', 'info', 82),
('치과 무통 마취', 'local', '시술', 'info', 80),
('수면 치료 치과', 'local', '시술', 'info', 79),
('응급 치과', 'local', '응급', 'info', 84),
('야간 치과', 'local', '응급', 'info', 83),
('주말 치과', 'local', '응급', 'info', 81),
('치과 진료 시간', 'local', '정보', 'info', 75),
('치과 의료비 공제', 'local', '비용', 'cost', 78),

-- ===== 추가 롱테일 키워드 (카테고리 혼합) =====
-- 임플란트 롱테일
('임플란트 후 식사', 'implant', '관리', 'info', 78),
('임플란트 후 운동', 'implant', '관리', 'info', 72),
('임플란트 후 술', 'implant', '관리', 'info', 74),
('임플란트 유지 비용', 'implant', '비용', 'cost', 76),
('임플란트 실패 확률', 'implant', '부작용', 'info', 73),
('임플란트 수면 마취', 'implant', '과정', 'info', 71),
('윗니 임플란트', 'implant', '부위별', 'info', 77),
('아랫니 임플란트', 'implant', '부위별', 'info', 76),
('임플란트 크라운 탈락', 'implant', '부작용', 'info', 70),
('임플란트 나사 풀림', 'implant', '부작용', 'info', 69),
('임플란트 보철 교체', 'implant', '관리', 'info', 68),
('임플란트 골이식 비용', 'implant', '비용', 'cost', 80),
('임플란트 치조골 흡수', 'implant', '부작용', 'info', 67),
('임플란트 금속 알레르기', 'implant', '부작용', 'info', 65),
('임플란트 CT 촬영', 'implant', '과정', 'info', 66),
('2024 임플란트 가격', 'implant', '비용', 'cost', 85),
('임플란트 의료보험', 'implant', '보험', 'cost', 84),
('65세 이상 임플란트 보험', 'implant', '보험', 'cost', 83),
('임플란트 vs 브릿지 비교', 'implant', '비교', 'comparison', 82),
('치조골 이식 수술', 'implant', '시술', 'info', 75),

-- 교정 롱테일
('교정 후 얼굴 변화', 'orthodontics', '효과', 'info', 82),
('교정 고통 정도', 'orthodontics', '통증', 'info', 78),
('교정 장치 종류별 비교', 'orthodontics', '비교', 'comparison', 80),
('교정 중 칫솔질', 'orthodontics', '관리', 'info', 74),
('교정 중 입냄새', 'orthodontics', '부작용', 'info', 70),
('교정 브라켓 탈락', 'orthodontics', '관리', 'info', 69),
('투명 교정 비용', 'orthodontics', '비용', 'cost', 88),
('인비절라인 vs 클리어', 'orthodontics', '비교', 'comparison', 77),
('교정 치료 단계', 'orthodontics', '과정', 'info', 79),
('교정 후 치아 벌어짐', 'orthodontics', '부작용', 'info', 72),
('2024 교정 비용', 'orthodontics', '비용', 'cost', 86),
('교정 의료비 공제', 'orthodontics', '비용', 'cost', 75),
('치아 교정 최적 나이', 'orthodontics', '대상', 'info', 81),
('교정 전 발치 이유', 'orthodontics', '과정', 'info', 76),
('교정 유지장치 기간', 'orthodontics', '관리', 'info', 77),
('미백 치약 효과', 'orthodontics', '미백', 'info', 73),
('미백 후 관리', 'orthodontics', '미백', 'info', 74),
('라미네이트 vs 크라운', 'orthodontics', '비교', 'comparison', 78),
('라미네이트 부작용', 'orthodontics', '미용', 'info', 75),
('잇몸 미백', 'orthodontics', '미용', 'info', 68),

-- 일반치료 롱테일
('충치 초기 증상', 'general', '충치', 'info', 86),
('충치 자연 치유', 'general', '충치', 'info', 80),
('충치 방치 위험', 'general', '충치', 'info', 84),
('신경 치료 후 크라운', 'general', '신경', 'info', 85),
('신경 치료 실패', 'general', '신경', 'info', 78),
('신경 치료 횟수', 'general', '신경', 'info', 76),
('사랑니 꼭 빼야 하나', 'general', '발치', 'info', 88),
('사랑니 발치 회복 기간', 'general', '발치', 'info', 86),
('사랑니 발치 후 음식', 'general', '발치', 'info', 84),
('사랑니 염증 증상', 'general', '발치', 'info', 82),
('이를 갈면 왜', 'general', '기타', 'info', 74),
('턱관절 소리', 'general', '기타', 'info', 78),
('턱관절 통증 원인', 'general', '기타', 'info', 79),
('잇몸 내려앉음 원인', 'general', '잇몸', 'info', 80),
('잇몸 염증 자연 치료', 'general', '잇몸', 'info', 76),
('치주 질환 예방', 'general', '잇몸', 'info', 77),
('치아 균열 증상', 'general', '증상', 'info', 75),
('치아 뿌리 노출', 'general', '증상', 'info', 73),
('잇몸 부음 원인', 'general', '증상', 'info', 81),
('치아 농양 증상', 'general', '증상', 'info', 72),

-- 예방관리 롱테일
('전동칫솔 vs 일반칫솔', 'prevention', '구강관리', 'comparison', 80),
('가글 효과', 'prevention', '구강관리', 'info', 76),
('구강세정기 추천', 'prevention', '구강관리', 'comparison', 78),
('치약 성분 확인법', 'prevention', '구강관리', 'info', 72),
('치과 정기검진 비용', 'prevention', '검진', 'cost', 77),
('어린이 충치 예방', 'prevention', '대상', 'info', 82),
('어린이 실란트 시기', 'prevention', '대상', 'info', 79),
('유치 빠지는 순서', 'prevention', '대상', 'info', 80),
('영구치 나는 시기', 'prevention', '대상', 'info', 78),
('임산부 잇몸 출혈', 'prevention', '대상', 'info', 76),
('임산부 치과 X레이', 'prevention', '대상', 'info', 75),
('당뇨와 잇몸 질환', 'prevention', '대상', 'info', 74),
('골다공증과 치아', 'prevention', '대상', 'info', 72),
('혈압약과 잇몸 출혈', 'prevention', '대상', 'info', 70),
('항응고제와 발치', 'prevention', '대상', 'info', 68),
('치아 건강 자가진단', 'prevention', '검진', 'info', 77),
('구취 검사', 'prevention', '검진', 'info', 73),
('잇몸 건강 체크법', 'prevention', '검진', 'info', 74),
('치과 검진 항목', 'prevention', '검진', 'info', 75),
('치아 보존 치료', 'prevention', '관리', 'info', 71),

-- 지역/상황 롱테일
('치과 첫 방문 준비', 'local', '경험', 'info', 79),
('치과 상담 질문 리스트', 'local', '경험', 'info', 77),
('치과 치료 순서', 'local', '정보', 'info', 76),
('치과 비용 절약법', 'local', '비용', 'cost', 82),
('의료비 연말정산', 'local', '비용', 'cost', 80),
('치과 실비보험 청구', 'local', '보험', 'cost', 81),
('치과 의료사고 대처', 'local', '정보', 'info', 70),
('세컨드 오피니언 치과', 'local', '경험', 'info', 74),
('해외 치과 치료 주의', 'local', '정보', 'info', 65),
('치과 영어 용어', 'local', '정보', 'info', 60),

-- ===== 심화 롱테일 키워드 추가 =====
('임플란트 시술 잘하는 곳 기준', 'implant', '병원선택', 'info', 80),
('임플란트 가격 비교 방법', 'implant', '비용', 'cost', 79),
('임플란트 시술 전 검사', 'implant', '과정', 'info', 74),
('임플란트 알레르기 검사', 'implant', '과정', 'info', 65),
('임플란트 보험 적용 조건', 'implant', '보험', 'cost', 82),
('임플란트 분할 납부', 'implant', '비용', 'cost', 71),
('원데이 임플란트', 'implant', '시술', 'info', 78),
('임플란트 보증서', 'implant', '보증', 'info', 68),
('치아 교정 얼굴형 변화', 'orthodontics', '효과', 'info', 80),
('양악수술 vs 교정', 'orthodontics', '비교', 'comparison', 75),
('교정 리테이너 종류', 'orthodontics', '관리', 'comparison', 73),
('교정 미세 조정', 'orthodontics', '과정', 'info', 67),
('교정 후 미백', 'orthodontics', '미백', 'info', 74),
('교정과 충치', 'orthodontics', '관리', 'info', 72),
('치아 삭제 없는 라미네이트', 'orthodontics', '미용', 'info', 76),
('충치 단계별 치료법', 'general', '충치', 'info', 83),
('이가 부러졌을 때', 'general', '외상', 'info', 82),
('치아 탈구 응급처치', 'general', '외상', 'info', 79),
('구강 건조증 원인', 'general', '증상', 'info', 76),
('혀 통증 원인', 'general', '증상', 'info', 72),
('입안 물집 원인', 'general', '증상', 'info', 74),
('치아 사이 음식 끼임', 'general', '증상', 'info', 71),
('치아 삭제 후 시림', 'general', '증상', 'info', 70),
('스케일링 보험 횟수', 'prevention', '보험', 'cost', 85),
('스케일링 통증', 'prevention', '스케일링', 'info', 78),
('스케일링 후 시림', 'prevention', '스케일링', 'info', 76),
('아이 첫 치과 방문', 'prevention', '대상', 'info', 81),
('유아 칫솔질 방법', 'prevention', '대상', 'info', 79),
('치과 공포 어린이', 'prevention', '대상', 'info', 77),
('의료비 소득공제 한도', 'local', '비용', 'cost', 78),
('치과 카드 할부', 'local', '비용', 'cost', 73),
('치과 무이자 할부', 'local', '비용', 'cost', 74),
('치과 방문 주기', 'local', '정보', 'info', 75),
('치과 예약 팁', 'local', '정보', 'info', 70),

-- ===== 시즌별/트렌드 키워드 =====
('여름 구강 관리', 'prevention', '시즌', 'info', 70),
('겨울 치아 시림', 'prevention', '시즌', 'info', 72),
('명절 후 치과', 'prevention', '시즌', 'info', 68),
('수능 후 교정', 'orthodontics', '시즌', 'info', 74),
('결혼 전 치아 관리', 'orthodontics', '시즌', 'info', 76),
('취업 면접 치아 관리', 'orthodontics', '시즌', 'info', 73),
('입학 전 구강검진', 'prevention', '시즌', 'info', 75),
('여행 중 치통 대처', 'prevention', '응급', 'info', 72),
('야외활동 치아 외상', 'prevention', '응급', 'info', 68),
('다이어트와 구강건강', 'prevention', '관리', 'info', 71),

-- ===== 최신 트렌드 키워드 =====
('3D 프린팅 치과', 'general', '기술', 'info', 72),
('AI 치과 진단', 'general', '기술', 'info', 70),
('디지털 치과', 'general', '기술', 'info', 74),
('CAD CAM 보철', 'general', '기술', 'info', 71),
('레이저 치과 치료', 'general', '기술', 'info', 73),
('줄기세포 치아 재생', 'general', '기술', 'info', 65),
('바이오세라믹', 'general', '기술', 'info', 63),
('치과 로봇 수술', 'general', '기술', 'info', 62),
('구강 마이크로바이옴', 'prevention', '관리', 'info', 64),
('프로바이오틱스 구강건강', 'prevention', '관리', 'info', 66),

-- ===== 추가 확충 키워드 200개+ (총 520개+) =====

-- ===== 임플란트 심화 (40개) =====
('임플란트 수술 후 붓기 기간', 'implant', '부작용', 'info', 81),
('임플란트 잇몸 내려앉음', 'implant', '부작용', 'info', 74),
('임플란트 수명 연장법', 'implant', '관리', 'info', 78),
('임플란트 틀니 차이', 'implant', '비교', 'comparison', 80),
('발치 후 임플란트 시기', 'implant', '과정', 'info', 84),
('임플란트 2개 비용', 'implant', '비용', 'cost', 77),
('임플란트 4개 비용', 'implant', '비용', 'cost', 75),
('임플란트 전체 비용 총정리', 'implant', '비용', 'cost', 82),
('임플란트 뼈이식 회복기간', 'implant', '시술', 'info', 79),
('임플란트 뼈이식 비용', 'implant', '비용', 'cost', 81),
('임플란트 잇몸 염증', 'implant', '부작용', 'info', 76),
('임플란트 나이 제한', 'implant', '대상', 'info', 73),
('20대 임플란트', 'implant', '대상', 'info', 71),
('30대 임플란트', 'implant', '대상', 'info', 72),
('40대 임플란트 비용', 'implant', '비용', 'cost', 74),
('50대 임플란트', 'implant', '대상', 'info', 76),
('임플란트 실패 후 재수술', 'implant', '시술', 'info', 70),
('임플란트 크라운 교체 주기', 'implant', '관리', 'info', 72),
('임플란트 스크류 고정 방식', 'implant', '시술', 'info', 65),
('임플란트 시멘트 고정', 'implant', '시술', 'info', 64),
('타이타늄 임플란트', 'implant', '종류', 'comparison', 70),
('임플란트 후 칫솔질 방법', 'implant', '관리', 'info', 77),
('임플란트 워터픽 사용', 'implant', '관리', 'info', 73),
('임플란트 치실 사용법', 'implant', '관리', 'info', 72),
('임플란트 정기검진 주기', 'implant', '관리', 'info', 75),
('임플란트 후 저림 증상', 'implant', '부작용', 'info', 68),
('임플란트 후 감각 이상', 'implant', '부작용', 'info', 67),
('임플란트 상부 보철물 가격', 'implant', '비용', 'cost', 73),
('2026 임플란트 보험 변경', 'implant', '보험', 'cost', 86),
('임플란트 건강보험 나이', 'implant', '보험', 'cost', 84),
('임플란트 본인부담금', 'implant', '보험', 'cost', 82),
('임플란트 치과 추천 기준', 'implant', '병원선택', 'info', 79),
('임플란트 상담 체크리스트', 'implant', '병원선택', 'info', 76),
('임플란트 후 음주 가능 시기', 'implant', '관리', 'info', 74),
('임플란트 후 커피', 'implant', '관리', 'info', 70),
('발치 즉시 임플란트 장단점', 'implant', '시술', 'info', 78),
('GBR 골유도재생술', 'implant', '시술', 'info', 72),
('임플란트 픽스쳐 종류', 'implant', '종류', 'comparison', 68),
('임플란트 어바트먼트', 'implant', '시술', 'info', 66),
('임플란트 후 이갈이', 'implant', '관리', 'info', 69),

-- ===== 교정/미용 심화 (35개) =====
('투명교정 장단점', 'orthodontics', '종류', 'comparison', 86),
('인비절라인 비용 2026', 'orthodontics', '비용', 'cost', 88),
('인비절라인 효과 기간', 'orthodontics', '기간', 'info', 82),
('인비절라인 유지장치', 'orthodontics', '관리', 'info', 78),
('클리어얼라이너', 'orthodontics', '브랜드', 'comparison', 76),
('교정 치아 이동 원리', 'orthodontics', '과정', 'info', 68),
('교정 치료 중 충치', 'orthodontics', '관리', 'info', 74),
('교정 후 잇몸 퇴축', 'orthodontics', '부작용', 'info', 71),
('교정 발치 4개', 'orthodontics', '과정', 'info', 76),
('교정 비발치', 'orthodontics', '과정', 'info', 78),
('교정 앵커 스크류', 'orthodontics', '시술', 'info', 72),
('교정 고무줄 역할', 'orthodontics', '관리', 'info', 70),
('치아교정 뼈 흡수', 'orthodontics', '부작용', 'info', 67),
('교정 중 입술 돌출', 'orthodontics', '부작용', 'info', 69),
('교정 전후 사진', 'orthodontics', '효과', 'info', 80),
('성인 부분교정 기간', 'orthodontics', '기간', 'info', 81),
('앞니 부분교정 비용', 'orthodontics', '비용', 'cost', 83),
('하악 교정', 'orthodontics', '종류', 'info', 72),
('상악 확장', 'orthodontics', '종류', 'info', 70),
('교정과 선택 기준', 'orthodontics', '병원선택', 'info', 75),
('라미네이트 10년 후', 'orthodontics', '미용', 'info', 74),
('라미네이트 재치료', 'orthodontics', '미용', 'info', 72),
('포세린 라미네이트', 'orthodontics', '미용', 'info', 70),
('잇몸 라인 불균형', 'orthodontics', '미용', 'info', 68),
('미백 종류별 비교', 'orthodontics', '미백', 'comparison', 79),
('레이저 미백 효과', 'orthodontics', '미백', 'info', 76),
('미백 유지 방법', 'orthodontics', '미백', 'info', 75),
('치아 본딩', 'orthodontics', '미용', 'info', 66),
('치아 컨투어링', 'orthodontics', '미용', 'info', 64),
('교정 보험 적용 조건', 'orthodontics', '비용', 'cost', 79),
('교정 실비 청구', 'orthodontics', '비용', 'cost', 77),
('교정 분납 할부', 'orthodontics', '비용', 'cost', 73),
('교정 중 스포츠', 'orthodontics', '관리', 'info', 66),
('악교정 수술', 'orthodontics', '종류', 'info', 73),
('투명교정 vs 설측교정', 'orthodontics', '비교', 'comparison', 80),

-- ===== 일반치료 심화 (40개) =====
('충치 단계', 'general', '충치', 'info', 88),
('충치 1단계 치료', 'general', '충치', 'info', 82),
('충치 2단계 치료', 'general', '충치', 'info', 80),
('충치 3단계 치료', 'general', '충치', 'info', 78),
('앞니 충치 치료', 'general', '충치', 'info', 81),
('어금니 충치 치료 비용', 'general', '충치', 'cost', 83),
('충치 예방법', 'general', '충치', 'info', 79),
('이차 충치', 'general', '충치', 'info', 74),
('사랑니 4개 동시 발치', 'general', '발치', 'info', 79),
('사랑니 발치 마취', 'general', '발치', 'info', 76),
('사랑니 발치 후 구멍', 'general', '발치', 'info', 80),
('사랑니 발치 후 출혈', 'general', '발치', 'info', 78),
('사랑니 발치 후 식사', 'general', '발치', 'info', 81),
('수평 매복 사랑니', 'general', '발치', 'info', 77),
('신경치료 후 통증 지속', 'general', '신경', 'info', 82),
('신경치료 몇 번 해야', 'general', '신경', 'info', 79),
('신경치료 안 하면', 'general', '신경', 'info', 81),
('신경치료 대안', 'general', '신경', 'info', 75),
('치아 균열 증후군', 'general', '증상', 'info', 73),
('치아 흔들리는 원인', 'general', '증상', 'info', 79),
('잇몸 고름', 'general', '잇몸', 'info', 78),
('잇몸 농양 치료', 'general', '잇몸', 'info', 76),
('잇몸 수술 종류', 'general', '잇몸', 'info', 74),
('잇몸 이식 수술', 'general', '잇몸', 'info', 72),
('치주 수술 후 관리', 'general', '잇몸', 'info', 71),
('스플린트 치료', 'general', '기타', 'info', 70),
('교합 치료', 'general', '기타', 'info', 68),
('턱관절 물리치료', 'general', '기타', 'info', 72),
('구강 칸디다증', 'general', '기타', 'info', 66),
('설태 원인', 'general', '기타', 'info', 64),
('혀 갈라짐 원인', 'general', '기타', 'info', 65),
('입천장 부음', 'general', '증상', 'info', 68),
('치아 법랑질 회복', 'general', '증상', 'info', 72),
('치아 산침식', 'general', '증상', 'info', 67),
('크라운 탈락 응급', 'general', '보철', 'info', 75),
('크라운 수명', 'general', '보철', 'info', 77),
('금 크라운 vs 지르코니아', 'general', '보철', 'comparison', 80),
('PFM 크라운', 'general', '보철', 'info', 69),
('임시 크라운 주의사항', 'general', '보철', 'info', 73),
('레진 충전 수명', 'general', '충치', 'info', 71),

-- ===== 예방/관리 심화 (35개) =====
('스케일링 자주 하면', 'prevention', '스케일링', 'info', 82),
('딥 스케일링', 'prevention', '스케일링', 'info', 79),
('스케일링 후 음식', 'prevention', '스케일링', 'info', 76),
('스케일링 출혈', 'prevention', '스케일링', 'info', 74),
('잇몸 마사지 방법', 'prevention', '구강관리', 'info', 70),
('혀 클리너 사용법', 'prevention', '구강관리', 'info', 68),
('구강청결제 종류별 효과', 'prevention', '구강관리', 'comparison', 75),
('치약 선택 가이드', 'prevention', '구강관리', 'info', 77),
('민감성 치아 치약', 'prevention', '구강관리', 'info', 74),
('잇몸 치약 추천 기준', 'prevention', '구강관리', 'info', 73),
('전동칫솔 올바른 사용법', 'prevention', '구강관리', 'info', 76),
('소닉케어 vs 오랄비', 'prevention', '구강관리', 'comparison', 72),
('치간 브러시 사이즈', 'prevention', '구강관리', 'info', 69),
('불소 치약 효과', 'prevention', '예방', 'info', 74),
('불소 부작용', 'prevention', '예방', 'info', 70),
('실란트 비용', 'prevention', '예방', 'cost', 77),
('실란트 수명', 'prevention', '예방', 'info', 75),
('어린이 실란트 보험', 'prevention', '예방', 'cost', 79),
('치과 파노라마 비용', 'prevention', '검진', 'cost', 72),
('CT 촬영 비용', 'prevention', '검진', 'cost', 71),
('임산부 스케일링', 'prevention', '대상', 'info', 78),
('임산부 발치 가능 시기', 'prevention', '대상', 'info', 76),
('수유기 치과 치료', 'prevention', '대상', 'info', 73),
('어린이 치아 외상 대처', 'prevention', '대상', 'info', 79),
('유치 발치 시기', 'prevention', '대상', 'info', 77),
('영구치 안 나는 이유', 'prevention', '대상', 'info', 74),
('과잉치', 'prevention', '대상', 'info', 72),
('매복치', 'prevention', '대상', 'info', 71),
('치아 건강 영양제', 'prevention', '관리', 'info', 73),
('비타민D와 치아', 'prevention', '관리', 'info', 68),
('칼슘과 치아 건강', 'prevention', '관리', 'info', 70),
('야식과 충치', 'prevention', '관리', 'info', 67),
('탄산음료 치아 영향', 'prevention', '관리', 'info', 72),
('커피 치아 착색', 'prevention', '관리', 'info', 74),
('와인 치아 착색 예방', 'prevention', '관리', 'info', 69),

-- ===== 지역/병원 심화 (20개) =====
('치과 진료비 영수증 보는법', 'local', '비용', 'info', 74),
('치과 과잉진료 구분법', 'local', '병원선택', 'info', 80),
('치과 세컨드 오피니언 방법', 'local', '병원선택', 'info', 76),
('대학병원 치과 vs 개인 치과', 'local', '병원선택', 'comparison', 79),
('치과 보존과 보철과 차이', 'local', '정보', 'info', 72),
('치과 전문의 종류', 'local', '정보', 'info', 75),
('구강외과 전문의', 'local', '정보', 'info', 71),
('소아치과 전문의', 'local', '정보', 'info', 73),
('치과 응급상황 대처', 'local', '응급', 'info', 81),
('치통 응급 진통제', 'local', '응급', 'info', 79),
('밤에 치통 대처법', 'local', '응급', 'info', 82),
('해외여행 중 치통', 'local', '응급', 'info', 68),
('치과 실비보험 가입 기준', 'local', '보험', 'cost', 78),
('치과 실손보험 청구 방법', 'local', '보험', 'cost', 80),
('치과 비급여 항목', 'local', '비용', 'info', 77),
('치과 급여 비급여 차이', 'local', '비용', 'info', 79),
('치과 초진 재진 비용', 'local', '비용', 'cost', 72),
('치과 예약 부도 페널티', 'local', '정보', 'info', 65),
('치과 진료 기록 열람', 'local', '정보', 'info', 67),
('치과 의료분쟁 절차', 'local', '정보', 'info', 66),

-- ===== 2026 트렌드 & 시즌 심화 (30개) =====
('2026 치과 보험 변경사항', 'prevention', '보험', 'cost', 88),
('2026 스케일링 보험 적용', 'prevention', '보험', 'cost', 85),
('2026 치아교정 비용', 'orthodontics', '비용', 'cost', 84),
('2026 치과 비급여 가격', 'local', '비용', 'cost', 80),
('AI 교합 분석', 'general', '기술', 'info', 68),
('3D 구강 스캐너', 'general', '기술', 'info', 72),
('디지털 임프레션', 'general', '기술', 'info', 69),
('원격 치과 상담', 'local', '기술', 'info', 70),
('치과 메타버스', 'local', '기술', 'info', 58),
('바이오호환 재료', 'general', '기술', 'info', 64),
('봄 환절기 구강관리', 'prevention', '시즌', 'info', 69),
('미세먼지 구강건강', 'prevention', '시즌', 'info', 67),
('장마철 구강관리', 'prevention', '시즌', 'info', 65),
('가을 건조 입마름', 'prevention', '시즌', 'info', 66),
('신학기 교정 시작', 'orthodontics', '시즌', 'info', 72),
('방학 치과 치료 계획', 'prevention', '시즌', 'info', 74),
('졸업시즌 미백', 'orthodontics', '시즌', 'info', 71),
('연말 치과 의료비 정산', 'local', '시즌', 'cost', 78),
('설날 전 치과 방문', 'prevention', '시즌', 'info', 66),
('추석 전 치과 점검', 'prevention', '시즌', 'info', 65),
('직장인 점심시간 치과', 'local', '시즌', 'info', 72),
('직장인 야간 치과 진료', 'local', '시즌', 'info', 74),
('군입대 전 치과 치료', 'prevention', '시즌', 'info', 76),
('유학 전 치과 검진', 'prevention', '시즌', 'info', 73),
('임신 준비 치과 검진', 'prevention', '시즌', 'info', 78),
('치아보험 가입 시기', 'prevention', '보험', 'cost', 76),
('치아보험 보장 범위', 'prevention', '보험', 'cost', 78),
('치과 실비 보장 변경', 'local', '보험', 'cost', 77),
('노인장기요양 구강관리', 'prevention', '대상', 'info', 65),
('치매 환자 구강관리', 'prevention', '대상', 'info', 63);
